### ISSUE TITLE
v0.1.1 doesn't contain the natural-compare-lite fix

### ISSUE THREAD

**Issue by buunguyen** [emgeee/gulp-natural-sort#3]
Not sure I miss something, but when I get v0.1.1 from NPM, it doesn't contain the fix from [this commit](https://github.com/emgeee/gulp-natural-sort/commit/94ac4596c8a8763ffdb6d2a07a8dc0054d5758fa). Thus the build fails as natural-compare-lite no longer defines `naturalCompare` method in `String`.

**Comment by emgeee** [comment]
Can you try removing `node_modules/gulp-natural-sort` then reinstalling it and let me know if it fixes it?

**Comment by buunguyen** [comment]
I just install from another folder then it gets the correct code. Not sure what happened before as I did remove the folder and even clear NPM cache. Looks like something wrong on my end.

Thanks for the prompt response!
